apiVersion: 1


# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: argus_influxdb
  # <string, required> datasource type. Required
  type: influxdb
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  isDefault: false
  # <string> url
  url: http://argus_influxdb:8086
  # <string> database name, if used
  secureJsonData: 
    token: $INFLUXDB_INIT_ADMIN_TOKEN
  jsonData:
    version: Flux
    organization: $ORG_NAME
    defaultBucket: $INFLUXDB_DB
    tlsSkipVerify: true
editable: true
