server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${ARGUS_URL}/loki/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true #FIXME: validate certifcate

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
