notifiers:
  - name: MicrosoftTeams
    type: teams
    uid: notifier1
    # either
    org_id: 1
    # or
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    # See `Supported Settings` section for settings supporter for each
    # alert notification type.
    settings:
      uploadImage: true
      url: <WEB_HOOK_URL>