version: '3.7'
services:
  telegraf: 
    restart: always
    image: telegraf:1.20-alpine
    container_name: argus_telegraf
    environment: 
      - ORG_NAME=$ORG_NAME
      - INFLUXDB_DB=$INFLUXDB_DB
      - INFLUXDB_URL=$INFLUXDB_URL
      - INFLUXDB_PASSWORD=$INFLUXDB_USER_PASSWORD
      - INFLUXDB_USER=$INFLUXDB_USER
    volumes: 
      - ./telegraf/:/etc/telegraf/
    