version: '3.7'
services:
  telegraf: 
    restart: always
    image: telegraf:1.20-alpine
    container_name: argus_telegraf
    environment: 
      - ORG_NAME=$ORG_NAME
      - INFLUXDB_URL=$INFLUXDB_URL
      - INFLUXDB_DB=$INFLUXDB_DB
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_INIT_ADMIN_TOKEN
    volumes: 
      - ./telegraf/:/etc/telegraf/
    